import React, { useMemo, useState } from 'react';
import saveAs from 'file-saver';
import { Icon } from '../ui/Icon';
import { Check, Modal, Notice } from '../ui/primitives';
import { cssFormatFor } from '../lib/fontConverter';
import { baseName } from '../lib/format';
import type { FontItem } from '../types/font';

interface CssExportModalProps {
  fonts: FontItem[];
  onClose: () => void;
  onNotify: (message: string) => void;
}

export function buildFontFaceCss(fonts: FontItem[], directory: string, groupFamilies: boolean): string {
  if (fonts.length === 0) return '/* No fonts loaded */';

  const prefix = directory.replace(/\/+$/, '');
  const rules = fonts.map((font) => {
    const file = `${baseName(font.fileName)}.${font.targetFormat}`;
    const family = groupFamilies ? font.family : `${font.family} ${font.subfamily}`.trim();
    const weight = groupFamilies ? font.weight : 400;
    const style = font.isItalic ? 'italic' : 'normal';

    return `@font-face {
  font-family: '${family}';
  src: url('${prefix}/${file}') ${cssFormatFor(font.targetFormat)};
  font-weight: ${weight};
  font-style: ${style};
  font-display: swap;
}`;
  });

  const families = [...new Set(fonts.map((font) => (groupFamilies ? font.family : `${font.family} ${font.subfamily}`.trim())))];

  return [
    '/* Generated by TypeForge — markdo27.github.io */',
    '',
    rules.join('\n\n'),
    '',
    '/* Usage */',
    ...families.map((family) => `/* font-family: '${family}'; */`),
    ''
  ].join('\n');
}

export const CssExportModal: React.FC<CssExportModalProps> = ({ fonts, onClose, onNotify }) => {
  const [directory, setDirectory] = useState('./fonts');
  const [groupFamilies, setGroupFamilies] = useState(true);

  const css = useMemo(
    () => buildFontFaceCss(fonts, directory, groupFamilies),
    [fonts, directory, groupFamilies]
  );

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(css);
      onNotify('CSS copied to the clipboard');
    } catch {
      onNotify('Could not reach the clipboard');
    }
  };

  return (
    <Modal
      index="F"
      title="@FONT-FACE CSS"
      subtitle={`${fonts.length} DECLARATION${fonts.length === 1 ? '' : 'S'}`}
      onClose={onClose}
      footer={
        <>
          <span className="note">PATHS ARE RELATIVE TO YOUR STYLESHEET</span>
          <div className="acts">
            <button type="button" className="btn" onClick={handleCopy}>
              <Icon name="copy" /> COPY
            </button>
            <button
              type="button"
              className="btn btn--solid"
              onClick={() => {
                saveAs(new Blob([css], { type: 'text/css;charset=utf-8' }), 'fonts.css');
                onNotify('Saved fonts.css');
              }}
            >
              <Icon name="download" /> DOWNLOAD FONTS.CSS
            </button>
          </div>
        </>
      }
    >
      <div className="cell">
        <div className="spread">
          <label className="field grow" style={{ maxWidth: 300 }}>
            <span>FONT DIRECTORY</span>
            <input
              className="input input--plain"
              value={directory}
              onChange={(event) => setDirectory(event.target.value)}
              placeholder="./fonts"
              spellCheck={false}
            />
          </label>
          <Check
            checked={groupFamilies}
            onChange={setGroupFamilies}
            label="ONE FAMILY NAME PER GROUP, WEIGHTS AS font-weight"
          />
        </div>

        <div style={{ marginTop: 18 }}>
          <Notice>
            {groupFamilies
              ? 'EVERY WEIGHT SHARES ONE font-family, SO CSS CAN PICK A WEIGHT WITH font-weight. THIS IS WHAT YOU WANT FOR THE WEB.'
              : 'EACH STYLE GETS ITS OWN font-family NAME. USE THIS WHEN A TOOL DOES NOT HANDLE WEIGHT GROUPING.'}
          </Notice>
        </div>
      </div>

      <div className="cell">
        <pre className="code">{css}</pre>
      </div>
    </Modal>
  );
};
